# Generated by Django 4.2 on 2023-04-18 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fitnes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="catcoach",
            options={
                "verbose_name": "Категория Тренер",
                "verbose_name_plural": "Категория Тренер",
            },
        ),
        migrations.AlterModelOptions(
            name="catdirection",
            options={
                "verbose_name": "Категория Направление",
                "verbose_name_plural": "Категория Направление",
            },
        ),
        migrations.AlterModelOptions(
            name="catsession",
            options={
                "verbose_name": "Категория Занятие",
                "verbose_name_plural": "Категория Занятие",
            },
        ),
        migrations.RemoveField(model_name="catsession", name="coach",),
        migrations.RemoveField(model_name="catsession", name="date_end",),
        migrations.RemoveField(model_name="catsession", name="date_start",),
        migrations.RemoveField(model_name="catsession", name="direction",),
        migrations.RemoveField(model_name="catsession", name="time_create",),
        migrations.RemoveField(model_name="catsession", name="time_update",),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_start", models.DateTimeField()),
                ("date_end", models.DateTimeField()),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                ("time_update", models.DateTimeField(auto_now=True)),
                ("detail_info", models.CharField(max_length=5000)),
                (
                    "coach",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fitnes.catcoach",
                    ),
                ),
                (
                    "direction",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fitnes.catdirection",
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fitnes.catsession",
                    ),
                ),
            ],
            options={"verbose_name": "Занятие", "verbose_name_plural": "Занятие",},
        ),
    ]
