# Generated by Django 4.2 on 2023-04-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitnes", "0002_alter_catcoach_options_alter_catdirection_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="detail_info",
            field=models.TextField(max_length=5000),
        ),
    ]
