# Generated by Django 4.2 on 2023-04-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitnes", "0003_alter_session_detail_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="title",
            field=models.CharField(default="default", max_length=255),
            preserve_default=False,
        ),
    ]
