# Generated by Django 4.2 on 2023-04-18 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fitnes", "0006_rename_name_session_session"),
    ]

    operations = [
        migrations.RemoveField(model_name="catsession", name="direction",),
        migrations.AddField(
            model_name="session",
            name="direction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="fitnes.catdirection",
            ),
        ),
    ]
